<?php
/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */
define( 'AS3CF_AWS_ACCESS_KEY_ID',     'AKIA5EOOVWLODNPJRWV6' );
define( 'AS3CF_AWS_SECRET_ACCESS_KEY', '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' );
require_once(dirname(__DIR__) . '/vendor/autoload.php');
require_once(dirname(__DIR__) . '/config/application.php');
require_once(ABSPATH . 'wp-settings.php');
